app/models/author.py
from sqlalchemy import Column, String, Integer

from settings import BaseModel


class Author(BaseModel):
    __tablename__ = "author"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100))

    def __repr__(self):
         u'%s' % self.name

app/models/book.py
from sqlalchemy import Table, Column, String, Integer, ForeignKey
from sqlalchemy.orm import relationship, backref

from settings import BaseModel


authors = Table('authors', BaseModel.metadata,
    Column('author_id', Integer, ForeignKey('author.id')),
    Column('book_id', Integer, ForeignKey('book.id'))
)


class Book(BaseModel):
    __tablename__ = "book"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100))
    authors = relationship('Author', secondary=authors,
                           backref=backref('books', lazy='dynamic'))

    def __repr__(self):
         u'%s' % self.name

app/models/user.py
import hashlib

from flask import session
from sqlalchemy import Column, Integer, String, Boolean

from settings import BaseModel, db_session


class User(BaseModel):
    __tablename__ = "user"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100))
    login = Column(String(50))
    password = Column(String(225))
    is_active = Column(Boolean, default=False)

    @staticmethod
    def hash_password(password):
        return hashlib.sha224(password).hexdigest()

    @classmethod
    def current(cls):
        if 'auth_user_id' in session:
            return db_session.query(cls)\
                             .filter(cls.id == session['auth_user_id'])

    def check_password(self, password):
        return self.password == User.hash_password(password)

    def __init__(self, *args, **kwargs):
        kwargs['password'] = User.hash_password(kwargs['password'])
        super(User, self).__init__(*args, **kwargs)

app/forms/author.py
from flask.ext.wtf import Form
from wtforms import TextField
from wtforms.validators import Required


class AuthorForm(Form):
    name = TextField('name', validators = [Required()])

app/forms/book.py
from flask.ext.wtf import Form
from wtforms import TextField, SelectMultipleField, widgets
from wtforms.validators import Required

from app.models.author import Author


class BookForm(Form):
    name = TextField('name', validators = [Required()])
    authors = SelectMultipleField('Authors',
        choices=[(author.id, author.name) for author in Author.query.all()],
        widget = widgets.ListWidget(prefix_label=False),
        option_widget = widgets.CheckboxInput()
    )

app/controllers/author.py
from flask import (Blueprint, render_template, request, redirect, url_for,
                   abort)
from sqlalchemy import desc

from app.helper.auth import auth_requierd
from app.forms.author import AuthorForm
from app.models.author import Author
from settings import db_session


bp = Blueprint("author", __name__, template_folder="../../templates/author")


@bp.route('/', methods=('GET',))
@auth_requierd
def all_authors():
    authors = db_session.query(Author).order_by(desc(Author.id))
    return render_template('author_all.html', page='author', authors=authors)

@bp.route('/delete/<int:author_id>/', methods=('GET',))
@auth_requierd
def delete_author(author_id):
    db_session.query(Author).filter(Author.id == author_id).delete()
    return redirect(url_for('author.all_authors'))

@bp.route('/update/<int:author_id>/', methods=('GET', 'POST'))
@auth_requierd
def update_author(author_id):
    author = db_session.query(Author).filter(Author.id == author_id).first()

    if not author:
        abort(404)

    form = AuthorForm(obj=author)

    if request.method == 'POST' and form.validate_on_submit():
        form.populate_obj(author)
        db_session.add(author)
        db_session.commit()

        return redirect(url_for('author.all_authors'))

    return render_template('author_form.html', page='author', form=form)

@bp.route('/create/', methods=('GET', 'POST'))
@auth_requierd
def create_author():
    form = AuthorForm()

    if request.method == 'POST' and form.validate_on_submit():
        author = Author()
        form.populate_obj(author)
        db_session.add(author)
        db_session.commit()

        return redirect(url_for('author.all_authors'))

    return render_template('author_form.html', page='author', form=form)

app/controllers/book.py
from flask import (Blueprint, render_template, redirect, url_for, request,
                   abort)
from sqlalchemy import desc

from app.helper.auth import auth_requierd
from app.forms.book import BookForm
from app.models.author import Author
from app.models.book import Book
from settings import db_session


bp = Blueprint("book", __name__, template_folder="../../templates/book")


@bp.route('/', methods=('GET',))
@auth_requierd
def all_books():
    books = db_session.query(Book).order_by(desc(Book.id))
    return render_template('book_all.html', page='book', books=books)

@bp.route('/delete/<int:book_id>/', methods=('GET',))
@auth_requierd
def delete_book(book_id):
    db_session.query(Book).filter(Book.id == book_id).delete()
    return redirect(url_for('book.all_books'))

@bp.route('/update/<int:book_id>/', methods=('GET', 'POST'))
@auth_requierd
def update_book(book_id):
    book = db_session.query(Book).filter(Book.id == book_id).first()

    if not book:
        abort(404)

    form = BookForm(obj=book)
    form.authors.data = [str(author.id) for author in book.authors]

    if request.method == 'POST' and form.name.data:
        old_authors = book.authors
        new_authors = db_session.query(Author).filter(
                        Author.id.in_(request.form.getlist('authors'))).all()

        removed_authors = set(old_authors) - set(new_authors)
        for author in removed_authors:
            book.authors.remove(author)

        added_authors = set(new_authors) - set(old_authors)
        for author in added_authors:
            book.authors.append(author)

        db_session.add(book)
        db_session.commit()

        return redirect(url_for('book.all_books'))

    return render_template('book_form.html', page='book', form=form)

@bp.route('/create/', methods=('GET', 'POST'))
@auth_requierd
def create_book():
    form = BookForm()

    if request.method == 'POST' and form.name.data:
        book = Book(name=form.name.data)

        book.authors = db_session.query(Author).filter(
                        Author.id.in_(request.form.getlist('authors'))).all()

        db_session.add(book)
        db_session.commit()

        return redirect(url_for('book.all_books'))

    return render_template('book_form.html', page='book', form=form)

app/controllers/home.py
from flask import Flask, render_template, redirect, session, request, url_for

from app.models.author import Author
from app.models.book import Book, authors
from app.models.user import User
from settings import db_session


app = Flask(__name__, template_folder='../../templates')


@app.route('/', methods=("GET",))
def home():
    return render_template("home.html", page="home")

@app.route('/search/', methods=('GET',))
def search_book():
    book_name = request.args.get('book')
    author_name = request.args.get('author')

    books = db_session.query(Book).outerjoin(authors, Author)\
                      .filter(Book.name == book_name)\
                      .filter(Author.name == author_name)

    return render_template("search.html", books=books, page="home")

@app.route('/login/', methods=("POST",))
def login():
    if request.method == 'POST':
        login = request.form['login']
        password = request.form['password']
        user = db_session.query(User).filter(User.login == login,
                                             User.is_active == True).first()

        if user and user.check_password(password):
            session['auth_user_id'] = user.id

    return redirect(request.referrer)

@app.route('/logout/', methods=("GET",))
def logout():
    session.pop('auth_user_id', None)
    return redirect(url_for('home'))

app/helper/auth.py
from functools import wraps

from flask import session, abort


def auth_requierd(f):
    @wraps(f)
    def wrapped(*args, **kwargs):
        if 'auth_user_id' not in session:
            abort(404)
        return f(*args, **kwargs)
    return wrapped

templates/author/author_all.html
{% extends "base.html" %}
{% block content %}
    <a type="button" class="btn btn-success" style="margin: 10px;" href="{{ url_for('author.create_author') }}">Add author</a>

    <table class="table">
        <thead>
            <th>Name</th>
            <th>Action</th>
        </thead>
        <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author.name }}</td>
                    <td>
                        <a href="{{ url_for('author.update_author', author_id=author.id) }}">Update</a>
                        <a href="{{ url_for('author.delete_author', author_id=author.id) }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/author/author_form.html
{% extends "base.html" %}
{% block content %}
    <form method="post" action="" role="form" style="margin-left: 20px;">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="exampleInputLogin">Name</label>
            {{ form.name }}
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock %}

templates/base.html
<html>
<head>
    <title>Test Flask Application</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
</head>
<body>
    <!-- HEADER -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-8">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('home') }}">Flask app</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8">
          <ul class="nav navbar-nav">
            <li {% if page == 'home' %}class="active"{% endif %}><a href="{{ url_for('home') }}">Home</a></li>
            {% if 'auth_user_id' in session %}
                <li {% if page == 'author' %}class="active"{% endif %}><a href="{{ url_for('author.all_authors') }}">Author</a></li>
                <li {% if page == 'book' %}class="active"{% endif %}><a href="{{ url_for('book.all_books') }}">Book</a></li>
                <li><a href="{{ url_for('logout') }}">Logout</a></li>
            {% else %}
                <li class="right" data-toggle="modal" data-target="#login">
                    <a href="javascript:void(0)">Login</a>
                </li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
    </nav>

    <!-- LOGIN BLOCK -->
    <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{{ url_for('login') }}" role="form">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Login</h4>
              </div>
              <div class="modal-body">
                  <div class="form-group">
                    <label for="exampleInputLogin">Login</label>
                    <input type="text" name="login" class="form-control" id="exampleInputLogin" placeholder="Enter login">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword">Password</label>
                    <input name="password" type="password" class="form-control" id="exampleInputPassword" placeholder="Enter password">
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Login</button>
              </div>
            </form>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div>

    <!-- CONTENT -->
    {% block content %}{% endblock %}

    <!-- JAVASCRIPT -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

templates/book/book_all.html
{% extends "base.html" %}
{% block content %}
    <a type="button" class="btn btn-success" style="margin: 10px;" href="{{ url_for('book.create_book') }}">Add book</a>

    <table class="table">
        <thead>
            <th>Name</th>
            <th>Action</th>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.name }}</td>
                    <td>
                        <a href="{{ url_for('book.update_book', book_id=book.id) }}">Update</a>
                        <a href="{{ url_for('book.delete_book', book_id=book.id) }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/book/book_form.html
{% extends "base.html" %}
{% block content %}
    <form method="post" action="" role="form" style="margin-left: 20px;">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <label for="exampleInputLogin">Name</label>
            {{ form.name }}<br>
            <label for="exampleInputLogin">Authors</label>
            {{ form.authors }}
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
    <div style="width: 700px; margin: 0 auto;">
        <h3>Search Book</h3>
        <form role="form" method="get" action="{{ url_for('search_book') }}">
          <div class="form-group">
            <label for="exampleInputBook">Book name</label>
            <input type="text" name="book" class="form-control" id="exampleInputBook">
          </div>
          <div class="form-group">
            <label for="exampleInputAuthor">Author name</label>
            <input type="text" name="author" class="form-control" id="exampleInputAuthor">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block content %}
    <h3 style="margin-left: 10px;">Books:</h3>
    <ul>
        {% for book in books %}
            <li>
                <b>{{ book.name }}</b>
                <div>
                    {% for author in book.authors %}
                        <i>{% if not loop.first %}, {% endif %}{{ author.name }}</i>
                    {% endfor %}
                </div>
            </li><br>
        {% endfor %}
    </ul>
{% endblock %}